import { describe, it, expect } from "vitest";
import { generateRepositoryAwards } from "@/lib/analytics/awards";
import { RepositoryAnalysis } from "@/types/domain";

describe("Repository Awards Engine", () => {
  it("should assign THE WORKHORSE to the repository with highest commit count", () => {
    const repos: RepositoryAnalysis[] = [
      {
        id: 1,
        name: "flagship-engine",
        fullName: "user/flagship-engine",
        isPrivate: false,
        isFork: false,
        isArchived: false,
        defaultBranch: "main",
        stars: 100,
        forks: 20,
        openIssues: 2,
        createdAt: "2023-01-01T00:00:00Z",
        lastPushedAt: "2026-08-01T00:00:00Z",
        primaryLanguage: "TypeScript",
        languages: [],
        commitCount: 150,
        additions: 20000,
        deletions: 5000,
        netLines: 15000,
        prsAuthored: 10,
        prsMerged: 10,
        issuesAuthored: 2,
        activitySpanDays: 500,
        daysSinceLastPush: 5,
        fetchStatus: "ok",
        fetchWarnings: [],
      },
      {
        id: 2,
        name: "side-toy",
        fullName: "user/side-toy",
        isPrivate: false,
        isFork: false,
        isArchived: false,
        defaultBranch: "main",
        stars: 5,
        forks: 0,
        openIssues: 0,
        createdAt: "2024-01-01T00:00:00Z",
        lastPushedAt: "2026-08-10T00:00:00Z",
        primaryLanguage: "Rust",
        languages: [],
        commitCount: 10,
        additions: 500,
        deletions: 100,
        netLines: 400,
        prsAuthored: 1,
        prsMerged: 1,
        issuesAuthored: 0,
        activitySpanDays: 100,
        daysSinceLastPush: 10,
        fetchStatus: "ok",
        fetchWarnings: [],
      },
    ];

    const awards = generateRepositoryAwards(repos, 160);
    const workhorse = awards.find((a) => a.id === "award-workhorse");

    expect(workhorse).toBeDefined();
    expect(workhorse?.repoFullName).toBe("user/flagship-engine");
  });

  it("should cap awards at 6 max and prioritize highest margin candidates", () => {
    const repos: RepositoryAnalysis[] = [
      {
        id: 1,
        name: "flagship-engine",
        fullName: "user/flagship-engine",
        isPrivate: false,
        isFork: false,
        isArchived: false,
        defaultBranch: "main",
        stars: 100,
        forks: 20,
        openIssues: 2,
        createdAt: "2023-01-01T00:00:00Z",
        lastPushedAt: "2026-08-01T00:00:00Z",
        primaryLanguage: "TypeScript",
        languages: [
          { name: "TypeScript", bytes: 50000, percentage: 50 },
          { name: "Rust", bytes: 30000, percentage: 30 },
          { name: "Python", bytes: 20000, percentage: 20 },
        ],
        commitCount: 200,
        additions: 50000,
        deletions: 10000,
        netLines: 40000,
        prsAuthored: 10,
        prsMerged: 10,
        issuesAuthored: 2,
        activitySpanDays: 600,
        daysSinceLastPush: 2,
        fetchStatus: "ok",
        fetchWarnings: [],
      },
      {
        id: 2,
        name: "dormant-beast",
        fullName: "user/dormant-beast",
        isPrivate: false,
        isFork: false,
        isArchived: false,
        defaultBranch: "main",
        stars: 2,
        forks: 0,
        openIssues: 0,
        createdAt: "2022-01-01T00:00:00Z",
        lastPushedAt: "2024-01-01T00:00:00Z",
        primaryLanguage: "C",
        languages: [],
        commitCount: 50,
        additions: 10000,
        deletions: 2000,
        netLines: 8000,
        prsAuthored: 0,
        prsMerged: 0,
        issuesAuthored: 0,
        activitySpanDays: 300,
        daysSinceLastPush: 950,
        fetchStatus: "ok",
        fetchWarnings: [],
      },
      {
        id: 3,
        name: "chaos-bomb",
        fullName: "user/chaos-bomb",
        isPrivate: false,
        isFork: false,
        isArchived: false,
        defaultBranch: "main",
        stars: 0,
        forks: 0,
        openIssues: 0,
        createdAt: "2025-01-01T00:00:00Z",
        lastPushedAt: "2026-08-20T00:00:00Z",
        primaryLanguage: "Go",
        languages: [],
        commitCount: 10,
        additions: 80000,
        deletions: 20000,
        netLines: 60000,
        prsAuthored: 0,
        prsMerged: 0,
        issuesAuthored: 0,
        activitySpanDays: 50,
        daysSinceLastPush: 10,
        fetchStatus: "ok",
        fetchWarnings: [],
      },
      {
        id: 4,
        name: "side-toy",
        fullName: "user/side-toy",
        isPrivate: false,
        isFork: false,
        isArchived: false,
        defaultBranch: "main",
        stars: 50,
        forks: 0,
        openIssues: 0,
        createdAt: "2025-01-01T00:00:00Z",
        lastPushedAt: "2026-08-25T00:00:00Z",
        primaryLanguage: "Python",
        languages: [],
        commitCount: 8,
        additions: 500,
        deletions: 100,
        netLines: 400,
        prsAuthored: 1,
        prsMerged: 1,
        issuesAuthored: 0,
        activitySpanDays: 100,
        daysSinceLastPush: 5,
        fetchStatus: "ok",
        fetchWarnings: [],
      },
      {
        id: 5,
        name: "comeback-repo",
        fullName: "user/comeback-repo",
        isPrivate: false,
        isFork: false,
        isArchived: false,
        defaultBranch: "main",
        stars: 1,
        forks: 0,
        openIssues: 0,
        createdAt: "2023-01-01T00:00:00Z",
        lastPushedAt: "2026-08-28T00:00:00Z",
        primaryLanguage: "Ruby",
        languages: [],
        commitCount: 25,
        additions: 2000,
        deletions: 500,
        netLines: 1500,
        prsAuthored: 2,
        prsMerged: 2,
        issuesAuthored: 0,
        activitySpanDays: 450,
        daysSinceLastPush: 2,
        fetchStatus: "ok",
        fetchWarnings: [],
      },
    ];

    const awards = generateRepositoryAwards(repos, 293);
    expect(awards.length).toBeLessThanOrEqual(6);
    expect(awards.length).toBeGreaterThan(0);
  });
});
